apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/jaydenaung/ibm/verify/ldap/ldap-data
